run:
  timeout: 5m
  modules-download-mode: vendor
linters:
  fast: false
  enable-all: true
  disable:
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - lll
    - gosec
    - funlen
    - godox
    - wsl
    - gocognit
    - maligned
    - goerr113
    - testpackage
    - gomnd
    - noctx
    - gci
linters-settings:
  gocyclo:
    min-complexity: 34
